// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Player.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Player.proto</summary>
public static partial class PlayerReflection {

  #region Descriptor
  /// <summary>File descriptor for Player.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PlayerReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgxQbGF5ZXIucHJvdG8ihgEKC1BsYXllclN0YXRzEg4KBmhlYWx0aBgBIAEo",
          "DRIPCgdzdGFtaW5hGAIgASgNEg0KBXNwZWVkGAMgASgCEhQKDGF0dGFja19z",
          "cGVlZBgEIAEoAhIVCg1hdHRhY2tfZGFtYWdlGAUgASgNEg0KBWFybW9yGAYg",
          "ASgNEgsKA2FvZRgHIAEoAiovCgpQbGF5ZXJUeXBlEgsKB1dBUlJJT1IQABII",
          "CgRNQUdFEAESCgoGQVJDSEVSEAJiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PlayerType), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PlayerStats), global::PlayerStats.Parser, new[]{ "Health", "Stamina", "Speed", "AttackSpeed", "AttackDamage", "Armor", "Aoe" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum PlayerType {
  [pbr::OriginalName("WARRIOR")] Warrior = 0,
  [pbr::OriginalName("MAGE")] Mage = 1,
  [pbr::OriginalName("ARCHER")] Archer = 2,
}

#endregion

#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class PlayerStats : pb::IMessage<PlayerStats>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PlayerStats> _parser = new pb::MessageParser<PlayerStats>(() => new PlayerStats());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PlayerStats> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PlayerReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerStats() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerStats(PlayerStats other) : this() {
    health_ = other.health_;
    stamina_ = other.stamina_;
    speed_ = other.speed_;
    attackSpeed_ = other.attackSpeed_;
    attackDamage_ = other.attackDamage_;
    armor_ = other.armor_;
    aoe_ = other.aoe_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerStats Clone() {
    return new PlayerStats(this);
  }

  /// <summary>Field number for the "health" field.</summary>
  public const int HealthFieldNumber = 1;
  private uint health_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Health {
    get { return health_; }
    set {
      health_ = value;
    }
  }

  /// <summary>Field number for the "stamina" field.</summary>
  public const int StaminaFieldNumber = 2;
  private uint stamina_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Stamina {
    get { return stamina_; }
    set {
      stamina_ = value;
    }
  }

  /// <summary>Field number for the "speed" field.</summary>
  public const int SpeedFieldNumber = 3;
  private float speed_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Speed {
    get { return speed_; }
    set {
      speed_ = value;
    }
  }

  /// <summary>Field number for the "attack_speed" field.</summary>
  public const int AttackSpeedFieldNumber = 4;
  private float attackSpeed_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float AttackSpeed {
    get { return attackSpeed_; }
    set {
      attackSpeed_ = value;
    }
  }

  /// <summary>Field number for the "attack_damage" field.</summary>
  public const int AttackDamageFieldNumber = 5;
  private uint attackDamage_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint AttackDamage {
    get { return attackDamage_; }
    set {
      attackDamage_ = value;
    }
  }

  /// <summary>Field number for the "armor" field.</summary>
  public const int ArmorFieldNumber = 6;
  private uint armor_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Armor {
    get { return armor_; }
    set {
      armor_ = value;
    }
  }

  /// <summary>Field number for the "aoe" field.</summary>
  public const int AoeFieldNumber = 7;
  private float aoe_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float Aoe {
    get { return aoe_; }
    set {
      aoe_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PlayerStats);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PlayerStats other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Health != other.Health) return false;
    if (Stamina != other.Stamina) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Speed, other.Speed)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AttackSpeed, other.AttackSpeed)) return false;
    if (AttackDamage != other.AttackDamage) return false;
    if (Armor != other.Armor) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Aoe, other.Aoe)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Health != 0) hash ^= Health.GetHashCode();
    if (Stamina != 0) hash ^= Stamina.GetHashCode();
    if (Speed != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Speed);
    if (AttackSpeed != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AttackSpeed);
    if (AttackDamage != 0) hash ^= AttackDamage.GetHashCode();
    if (Armor != 0) hash ^= Armor.GetHashCode();
    if (Aoe != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Aoe);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Health != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Health);
    }
    if (Stamina != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Stamina);
    }
    if (Speed != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(Speed);
    }
    if (AttackSpeed != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(AttackSpeed);
    }
    if (AttackDamage != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(AttackDamage);
    }
    if (Armor != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(Armor);
    }
    if (Aoe != 0F) {
      output.WriteRawTag(61);
      output.WriteFloat(Aoe);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Health != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Health);
    }
    if (Stamina != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Stamina);
    }
    if (Speed != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(Speed);
    }
    if (AttackSpeed != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(AttackSpeed);
    }
    if (AttackDamage != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(AttackDamage);
    }
    if (Armor != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(Armor);
    }
    if (Aoe != 0F) {
      output.WriteRawTag(61);
      output.WriteFloat(Aoe);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Health != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Health);
    }
    if (Stamina != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Stamina);
    }
    if (Speed != 0F) {
      size += 1 + 4;
    }
    if (AttackSpeed != 0F) {
      size += 1 + 4;
    }
    if (AttackDamage != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AttackDamage);
    }
    if (Armor != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Armor);
    }
    if (Aoe != 0F) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PlayerStats other) {
    if (other == null) {
      return;
    }
    if (other.Health != 0) {
      Health = other.Health;
    }
    if (other.Stamina != 0) {
      Stamina = other.Stamina;
    }
    if (other.Speed != 0F) {
      Speed = other.Speed;
    }
    if (other.AttackSpeed != 0F) {
      AttackSpeed = other.AttackSpeed;
    }
    if (other.AttackDamage != 0) {
      AttackDamage = other.AttackDamage;
    }
    if (other.Armor != 0) {
      Armor = other.Armor;
    }
    if (other.Aoe != 0F) {
      Aoe = other.Aoe;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Health = input.ReadUInt32();
          break;
        }
        case 16: {
          Stamina = input.ReadUInt32();
          break;
        }
        case 29: {
          Speed = input.ReadFloat();
          break;
        }
        case 37: {
          AttackSpeed = input.ReadFloat();
          break;
        }
        case 40: {
          AttackDamage = input.ReadUInt32();
          break;
        }
        case 48: {
          Armor = input.ReadUInt32();
          break;
        }
        case 61: {
          Aoe = input.ReadFloat();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Health = input.ReadUInt32();
          break;
        }
        case 16: {
          Stamina = input.ReadUInt32();
          break;
        }
        case 29: {
          Speed = input.ReadFloat();
          break;
        }
        case 37: {
          AttackSpeed = input.ReadFloat();
          break;
        }
        case 40: {
          AttackDamage = input.ReadUInt32();
          break;
        }
        case 48: {
          Armor = input.ReadUInt32();
          break;
        }
        case 61: {
          Aoe = input.ReadFloat();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
